### ISSUE TITLE
Multiple bugs and issues

### ISSUE THREAD

**Issue by Andre601** [harry0198/InfoHeads-mvn#1]
I discovered a small bug

## Issue
When typing `/infoheads reload` I get `/infoheads` as a response right after the confirm message of the reload indicating that there is a missing `return true` or it just returns false.

## Other small issues
Why is the plugin called InfoHeads when it can be used with any block?
And could you perhaps add that removing the head/block removes the setting from the config?

**Comment by harry0198** [comment]
Next update pretty much covers all basis;

- [x]  Fixed the "echoing" on the commands

- [x]  On breakage, it will remove the head as well as a deletion command.

As for the plugin naming, it's what the plugin initially revolved around when it was initially created.

Thanks for the reports!
