### ISSUE TITLE
HeadDatabaseAPI being included in jar

### ISSUE THREAD

**Issue by Rickebo** [harry0198/InfoHeads-mvn#10]
HeadDatabaseAPI is included in the jar file of InfoHeads, which results in other plugins using HeadDatabaseAPI not working correctly. I added `<scope>provided</scope>` to the HeadDatabaseAPI dependency fixes this issue.

https://github.com/harry0198/InfoHeads-mvn/blob/9d153b1bec0f9d463226a3bed7f3849416e9bcf7/pom.xml#L66-L70

**Comment by harry0198** [comment]
This has been added to the codebase, thank you for letting me know. See (https://github.com/harry0198/InfoHeads-mvn/commit/b072ac756e055f72f38e086bebbb72eba62aea3a)
